import type { CostCategory, RegisterCost } from "./types";
import { daysAgoIso } from "@/lib/jalali";

/**
 * دادهٔ نمونهٔ هزینه‌ها و درآمدها (فاز ۵)
 * دسته‌های هزینه و درآمد عمداً جدا از دسته‌های کالا/خدمت هستند.
 */

export const SEED_COST_CATEGORIES: CostCategory[] = [
  { id: "cat-e-1", name: "اجاره", kind: "EXPENSE", createdAt: daysAgoIso(60), updatedAt: daysAgoIso(60) },
  { id: "cat-e-2", name: "حقوق", kind: "EXPENSE", createdAt: daysAgoIso(60), updatedAt: daysAgoIso(60) },
  { id: "cat-e-3", name: "قبوض", kind: "EXPENSE", createdAt: daysAgoIso(60), updatedAt: daysAgoIso(60) },
  { id: "cat-e-4", name: "حمل و نقل", kind: "EXPENSE", createdAt: daysAgoIso(55), updatedAt: daysAgoIso(55) },
  { id: "cat-e-5", name: "خرید تجهیزات", kind: "EXPENSE", createdAt: daysAgoIso(55), updatedAt: daysAgoIso(55) },
  { id: "cat-e-6", name: "تبلیغات", kind: "EXPENSE", createdAt: daysAgoIso(50), updatedAt: daysAgoIso(50) },
  { id: "cat-e-7", name: "سایر", kind: "EXPENSE", createdAt: daysAgoIso(50), updatedAt: daysAgoIso(50) },
  { id: "cat-i-1", name: "فروش خدمات", kind: "INCOME", createdAt: daysAgoIso(60), updatedAt: daysAgoIso(60) },
  { id: "cat-i-2", name: "درآمد جانبی", kind: "INCOME", createdAt: daysAgoIso(60), updatedAt: daysAgoIso(60) },
  { id: "cat-i-3", name: "سود", kind: "INCOME", createdAt: daysAgoIso(55), updatedAt: daysAgoIso(55) },
  { id: "cat-i-4", name: "سایر", kind: "INCOME", createdAt: daysAgoIso(55), updatedAt: daysAgoIso(55) },
];

export const SEED_COSTS: RegisterCost[] = [
  {
    id: "rc-1",
    type: "EXPENSE",
    title: "اجارهٔ مغازه",
    categoryId: "cat-e-1",
    amount: 15_000_000,
    date: daysAgoIso(6),
    time: "09:00",
    description: "اجارهٔ ماهانهٔ واحد تجاری",
    createdAt: daysAgoIso(6),
    updatedAt: daysAgoIso(6),
  },
  {
    id: "rc-2",
    type: "EXPENSE",
    title: "حقوق فروشنده",
    categoryId: "cat-e-2",
    amount: 8_500_000,
    date: daysAgoIso(4),
    time: "18:30",
    createdAt: daysAgoIso(4),
    updatedAt: daysAgoIso(4),
  },
  {
    id: "rc-3",
    type: "EXPENSE",
    title: "قبض برق و تلفن",
    categoryId: "cat-e-3",
    amount: 1_200_000,
    date: daysAgoIso(2),
    time: "11:15",
    createdAt: daysAgoIso(2),
    updatedAt: daysAgoIso(2),
  },
  {
    id: "rc-4",
    type: "EXPENSE",
    title: "کرایهٔ حمل بار",
    categoryId: "cat-e-4",
    amount: 450_000,
    date: daysAgoIso(1),
    time: "14:40",
    description: "جابجایی اجناس از انبار به مغازه",
    createdAt: daysAgoIso(1),
    updatedAt: daysAgoIso(1),
  },
  {
    id: "rc-5",
    type: "EXPENSE",
    title: "خرید قفسهٔ فروشگاهی",
    categoryId: "cat-e-5",
    amount: 6_800_000,
    date: daysAgoIso(12),
    time: "16:20",
    createdAt: daysAgoIso(12),
    updatedAt: daysAgoIso(12),
  },
  {
    id: "rc-6",
    type: "EXPENSE",
    title: "تبلیغ در شبکهٔ اجتماعی",
    categoryId: "cat-e-6",
    amount: 2_500_000,
    date: daysAgoIso(9),
    time: "10:00",
    createdAt: daysAgoIso(9),
    updatedAt: daysAgoIso(9),
  },
  {
    id: "rc-7",
    type: "INCOME",
    title: "فروش خدمات نصب",
    categoryId: "cat-i-1",
    amount: 22_000_000,
    date: daysAgoIso(3),
    time: "13:00",
    description: "پروژهٔ نصب تجهیزات برای مشتری شرکتی",
    createdAt: daysAgoIso(3),
    updatedAt: daysAgoIso(3),
  },
  {
    id: "rc-8",
    type: "INCOME",
    title: "اجارهٔ انبار",
    categoryId: "cat-i-2",
    amount: 3_200_000,
    date: daysAgoIso(8),
    time: "09:45",
    createdAt: daysAgoIso(8),
    updatedAt: daysAgoIso(8),
  },
  {
    id: "rc-9",
    type: "INCOME",
    title: "سود فروش عمده",
    categoryId: "cat-i-3",
    amount: 5_400_000,
    date: daysAgoIso(15),
    time: "17:10",
    createdAt: daysAgoIso(15),
    updatedAt: daysAgoIso(15),
  },
  {
    id: "rc-10",
    type: "EXPENSE",
    title: "خرید لوازم پذیرایی",
    categoryId: "cat-e-7",
    amount: 350_000,
    date: daysAgoIso(0),
    time: "08:20",
    createdAt: daysAgoIso(0),
    updatedAt: daysAgoIso(0),
  },
];
