import type { Invoice } from "./types";
import { daysAgoIso } from "@/lib/jalali";

/**
 * دادهٔ نمونهٔ فاکتورها (فاز ۴)
 *
 * سازگاری با سایر بذرها:
 * - اثر انباری این فاکتورها در `src/inventory/seed.ts` با حرکات منبع
 *   INVOICE و شناسهٔ فاکتور ثبت شده و موجودی کالاها با آن‌ها جمع بسته است.
 * - اثر مالی فاکتورهای نسیه/اقساطی در `src/book/seed.ts` با رکوردهای
 *   متصل به فاکتور (تگ invoiceId) ثبت شده است.
 * - فاکتور نقدی و پیش‌فاکتور هیچ رکورد مالی‌ای ندارند.
 */

export const SEED_INVOICES: Invoice[] = [
  /* ------------------------- فاکتور فروش نقدی ------------------------- */
  {
    id: "inv-1001",
    invoiceNumber: "INV-1001",
    type: "SELL",
    personId: "p-gen",
    date: daysAgoIso(12),
    time: "10:30",
    items: [
      {
        id: "ii-1001a",
        productId: "p-101",
        productType: "PRODUCT",
        nameSnapshot: "روغن آفتاب‌گردان یک لیتری",
        quantity: 6,
        unit: "بطری",
        unitPrice: 128_000,
        discount: 0,
        total: 768_000,
      },
      {
        id: "ii-1001b",
        productId: "s-201",
        productType: "SERVICE",
        nameSnapshot: "نصب ویندوز و درایورها",
        quantity: 1,
        unitPrice: 350_000,
        discount: 0,
        total: 350_000,
      },
    ],
    grossTotal: 1_118_000,
    itemsDiscount: 0,
    discount: 38_000,
    subtotal: 1_080_000,
    taxEnabled: true,
    taxRate: 9,
    taxAmount: 97_200,
    extraCosts: [{ id: "ec-1001", title: "هزینهٔ حمل", amount: 25_000 }],
    totalAmount: 1_202_200,
    paymentType: "CASH",
    paidAmount: 1_202_200,
    shippingStatus: "SENT",
    description: "فروش حضوری همراه با نصب سیستم",
    status: "PAID",
    createdAt: daysAgoIso(12),
    updatedAt: daysAgoIso(12),
  },

  /* ------------------------- فاکتور فروش نسیه ------------------------- */
  {
    id: "inv-1002",
    invoiceNumber: "INV-1002",
    type: "SELL",
    personId: "p-4",
    date: daysAgoIso(5),
    time: "17:15",
    items: [
      {
        id: "ii-1002a",
        productId: "p-104",
        productType: "PRODUCT",
        nameSnapshot: "برنج ایرانی ۱۰ کیلویی",
        quantity: 5,
        unit: "کیسه",
        unitPrice: 980_000,
        discount: 0,
        total: 4_900_000,
      },
      {
        id: "ii-1002b",
        productId: "p-105",
        productType: "PRODUCT",
        nameSnapshot: "تیشرت نخی مردانه",
        quantity: 4,
        unit: "عدد",
        unitPrice: 290_000,
        discount: 0,
        total: 1_160_000,
      },
    ],
    grossTotal: 6_060_000,
    itemsDiscount: 0,
    discount: 0,
    subtotal: 6_060_000,
    taxEnabled: false,
    taxRate: 9,
    taxAmount: 0,
    extraCosts: [],
    totalAmount: 6_060_000,
    paymentType: "CREDIT",
    paidAmount: 0,
    shippingStatus: "SENT",
    note: "تسویه تا پایان ماه",
    status: "UNPAID",
    createdAt: daysAgoIso(5),
    updatedAt: daysAgoIso(5),
  },

  /* ------------------------- فاکتور فروش اقساطی ------------------------- */
  {
    id: "inv-1003",
    invoiceNumber: "INV-1003",
    type: "SELL",
    personId: "p-1",
    date: daysAgoIso(2),
    time: "12:40",
    items: [
      {
        id: "ii-1003a",
        productId: "p-101",
        productType: "PRODUCT",
        nameSnapshot: "روغن آفتاب‌گردان یک لیتری",
        quantity: 20,
        unit: "بطری",
        unitPrice: 128_000,
        discount: 200_000,
        total: 2_360_000,
      },
      {
        id: "ii-1003b",
        productId: "p-102",
        productType: "PRODUCT",
        nameSnapshot: "کابل شارژ تایپ‌سی",
        quantity: 10,
        unit: "عدد",
        unitPrice: 110_000,
        discount: 0,
        total: 1_100_000,
      },
      {
        id: "ii-1003c",
        productId: "p-104",
        productType: "PRODUCT",
        nameSnapshot: "برنج ایرانی ۱۰ کیلویی",
        quantity: 8,
        unit: "کیسه",
        unitPrice: 980_000,
        discount: 0,
        total: 7_840_000,
      },
    ],
    grossTotal: 11_500_000,
    itemsDiscount: 200_000,
    discount: 1_300_000,
    subtotal: 10_000_000,
    taxEnabled: false,
    taxRate: 9,
    taxAmount: 0,
    extraCosts: [],
    totalAmount: 10_000_000,
    paymentType: "INSTALLMENT",
    paidAmount: 4_000_000,
    shippingStatus: "NOT_SENT",
    description: "فروش عمده — بازپرداخت طی سه قسط",
    status: "PARTIAL",
    createdAt: daysAgoIso(2),
    updatedAt: daysAgoIso(2),
  },

  /* ------------------------- فاکتور خرید نسیه ------------------------- */
  {
    id: "inv-1004",
    invoiceNumber: "INV-1004",
    type: "BUY",
    personId: "p-2",
    date: daysAgoIso(9),
    time: "09:20",
    items: [
      {
        id: "ii-1004a",
        productId: "p-101",
        productType: "PRODUCT",
        nameSnapshot: "روغن آفتاب‌گردان یک لیتری",
        quantity: 12,
        unit: "بطری",
        unitPrice: 95_000,
        discount: 0,
        total: 1_140_000,
      },
      {
        id: "ii-1004b",
        productId: "p-102",
        productType: "PRODUCT",
        nameSnapshot: "کابل شارژ تایپ‌سی",
        quantity: 10,
        unit: "عدد",
        unitPrice: 65_000,
        discount: 0,
        total: 650_000,
      },
      {
        id: "ii-1004c",
        productId: "p-104",
        productType: "PRODUCT",
        nameSnapshot: "برنج ایرانی ۱۰ کیلویی",
        quantity: 6,
        unit: "کیسه",
        unitPrice: 850_000,
        discount: 0,
        total: 5_100_000,
      },
    ],
    grossTotal: 6_890_000,
    itemsDiscount: 0,
    discount: 0,
    subtotal: 6_890_000,
    taxEnabled: false,
    taxRate: 9,
    taxAmount: 0,
    extraCosts: [],
    totalAmount: 6_890_000,
    paymentType: "CREDIT",
    paidAmount: 0,
    shippingStatus: "SENT",
    status: "UNPAID",
    createdAt: daysAgoIso(9),
    updatedAt: daysAgoIso(9),
  },

  /* ------------------------- فاکتور خرید نقدی ------------------------- */
  {
    id: "inv-1005",
    invoiceNumber: "INV-1005",
    type: "BUY",
    personId: "p-2",
    date: daysAgoIso(1),
    time: "11:05",
    items: [
      {
        id: "ii-1005a",
        productId: "p-105",
        productType: "PRODUCT",
        nameSnapshot: "تیشرت نخی مردانه",
        quantity: 10,
        unit: "عدد",
        unitPrice: 180_000,
        discount: 0,
        total: 1_800_000,
      },
    ],
    grossTotal: 1_800_000,
    itemsDiscount: 0,
    discount: 0,
    subtotal: 1_800_000,
    taxEnabled: false,
    taxRate: 9,
    taxAmount: 0,
    extraCosts: [],
    totalAmount: 1_800_000,
    paymentType: "CASH",
    paidAmount: 1_800_000,
    shippingStatus: "SENT",
    status: "PAID",
    createdAt: daysAgoIso(1),
    updatedAt: daysAgoIso(1),
  },

  /* ------------------------- فاکتور فروش با تسویهٔ چکی (فاز ۵) ------------------------- */
  {
    id: "inv-1007",
    invoiceNumber: "INV-1007",
    type: "SELL",
    personId: "p-1",
    date: daysAgoIso(3),
    time: "13:20",
    items: [
      {
        id: "ii-1007a",
        productId: "p-101",
        productType: "PRODUCT",
        nameSnapshot: "روغن آفتاب‌گردان یک لیتری",
        quantity: 10,
        unit: "بطری",
        unitPrice: 128_000,
        discount: 0,
        total: 1_280_000,
      },
      {
        id: "ii-1007b",
        productId: "p-104",
        productType: "PRODUCT",
        nameSnapshot: "برنج ایرانی ۱۰ کیلویی",
        quantity: 2,
        unit: "کیسه",
        unitPrice: 980_000,
        discount: 0,
        total: 1_960_000,
      },
    ],
    grossTotal: 3_240_000,
    itemsDiscount: 0,
    discount: 0,
    subtotal: 3_240_000,
    taxEnabled: false,
    taxRate: 9,
    taxAmount: 0,
    extraCosts: [],
    totalAmount: 3_240_000,
    paymentType: "CHEQUE",
    paidAmount: 0,
    shippingStatus: "NOT_SENT",
    description: "تسویه با چک صیادی",
    status: "CHEQUE_PENDING",
    createdAt: daysAgoIso(3),
    updatedAt: daysAgoIso(3),
  },

  /* ------------------------- فاکتور خرید با تسویهٔ چکی (فاز ۵) ------------------------- */
  {
    id: "inv-1008",
    invoiceNumber: "INV-1008",
    type: "BUY",
    personId: "p-2",
    date: daysAgoIso(4),
    time: "10:10",
    items: [
      {
        id: "ii-1008a",
        productId: "p-102",
        productType: "PRODUCT",
        nameSnapshot: "کابل شارژ تایپ‌سی",
        quantity: 20,
        unit: "عدد",
        unitPrice: 65_000,
        discount: 0,
        total: 1_300_000,
      },
    ],
    grossTotal: 1_300_000,
    itemsDiscount: 0,
    discount: 0,
    subtotal: 1_300_000,
    taxEnabled: false,
    taxRate: 9,
    taxAmount: 0,
    extraCosts: [],
    totalAmount: 1_300_000,
    paymentType: "CHEQUE",
    paidAmount: 0,
    shippingStatus: "SENT",
    status: "CHEQUE_PENDING",
    createdAt: daysAgoIso(4),
    updatedAt: daysAgoIso(4),
  },

  /* ------------------------- پیش‌فاکتور ------------------------- */
  {
    id: "inv-1006",
    invoiceNumber: "INV-1006",
    type: "DRAFT",
    personId: "p-3",
    date: daysAgoIso(1),
    time: "16:45",
    items: [
      {
        id: "ii-1006a",
        productId: "p-101",
        productType: "PRODUCT",
        nameSnapshot: "روغن آفتاب‌گردان یک لیتری",
        quantity: 10,
        unit: "بطری",
        unitPrice: 128_000,
        discount: 0,
        total: 1_280_000,
      },
      {
        id: "ii-1006b",
        productId: "s-202",
        productType: "SERVICE",
        nameSnapshot: "مشاوره مالی یک ساعته",
        quantity: 1,
        unitPrice: 500_000,
        discount: 0,
        total: 500_000,
      },
    ],
    grossTotal: 1_780_000,
    itemsDiscount: 0,
    discount: 80_000,
    subtotal: 1_700_000,
    taxEnabled: false,
    taxRate: 9,
    taxAmount: 0,
    extraCosts: [],
    totalAmount: 1_700_000,
    paymentType: "CASH",
    paidAmount: 0,
    description: "پیش‌فاکتور برای استعلام قیمت مشتری",
    status: "DRAFT",
    createdAt: daysAgoIso(1),
    updatedAt: daysAgoIso(1),
  },
];
