import type { Product, ProductCategory, StockMovement } from "./types";
import { daysAgoIso } from "@/lib/jalali";

/**
 * دادهٔ نمونهٔ فاز ۳ — صرفاً برای تجربهٔ واقعی رابط کاربری.
 * شامل کالای سالم، رو به اتمام و ناموجود، چند خدمت و حرکات انبار.
 */

const nowIso = () => new Date().toISOString();

export const SEED_CATEGORIES: ProductCategory[] = [
  { id: "cat-1", name: "مواد غذایی", createdAt: daysAgoIso(90), updatedAt: daysAgoIso(90) },
  { id: "cat-2", name: "پوشاک", createdAt: daysAgoIso(90), updatedAt: daysAgoIso(90) },
  { id: "cat-3", name: "لوازم جانبی", createdAt: daysAgoIso(80), updatedAt: daysAgoIso(80) },
  { id: "cat-4", name: "خدمات فنی", createdAt: daysAgoIso(70), updatedAt: daysAgoIso(70) },
  { id: "cat-5", name: "خدمات مشاوره", createdAt: daysAgoIso(70), updatedAt: daysAgoIso(70) },
  { id: "cat-6", name: "سایر", createdAt: daysAgoIso(60), updatedAt: daysAgoIso(60) },
];

export const SEED_PRODUCTS: Product[] = [
  // کالای سالم
  {
    id: "p-101",
    type: "PRODUCT",
    name: "روغن آفتاب‌گردان یک لیتری",
    description: "روغن مایع مخصوص پخت‌وپز",
    categoryId: "cat-1",
    barcode: "6210001112223",
    unit: "بطری",
    initialStock: 48,
    currentStock: 18,
    purchasePrice: 95_000,
    salePrice: 128_000,
    reorderPoint: 12,
    showInOnlinePriceList: true,
    minimumOrderQuantity: 2,
    createdAt: daysAgoIso(40),
    updatedAt: daysAgoIso(40),
  },
  // کالای رو به اتمام
  {
    id: "p-102",
    type: "PRODUCT",
    name: "کابل شارژ تایپ‌سی",
    description: "کابل یک متری با روکش مقاوم",
    categoryId: "cat-3",
    barcode: "6210003334445",
    unit: "عدد",
    initialStock: 10,
    currentStock: 23,
    purchasePrice: 65_000,
    salePrice: 110_000,
    reorderPoint: 5,
    showInOnlinePriceList: true,
    minimumOrderQuantity: 1,
    createdAt: daysAgoIso(35),
    updatedAt: daysAgoIso(35),
  },
  // کالای ناموجود
  {
    id: "p-103",
    type: "PRODUCT",
    name: "هدفون بی‌سیم",
    description: "هدفون بلوتوثی با کیس شارژ",
    categoryId: "cat-3",
    barcode: "6210005556667",
    unit: "عدد",
    initialStock: 5,
    currentStock: 0,
    purchasePrice: 750_000,
    salePrice: 1_150_000,
    reorderPoint: 2,
    showInOnlinePriceList: false,
    createdAt: daysAgoIso(30),
    updatedAt: daysAgoIso(30),
  },
  // کالای دیگر
  {
    id: "p-104",
    type: "PRODUCT",
    name: "برنج ایرانی ۱۰ کیلویی",
    description: "برنج درجه یک شمال",
    categoryId: "cat-1",
    barcode: "6210007778889",
    unit: "کیسه",
    initialStock: 20,
    currentStock: 8,
    purchasePrice: 850_000,
    salePrice: 980_000,
    reorderPoint: 6,
    showInOnlinePriceList: true,
    minimumOrderQuantity: 1,
    createdAt: daysAgoIso(25),
    updatedAt: daysAgoIso(25),
  },
  {
    id: "p-105",
    type: "PRODUCT",
    name: "تیشرت نخی مردانه",
    description: "سایزهای مختلف، رنگ‌بندی کامل",
    categoryId: "cat-2",
    barcode: "6210009990001",
    unit: "عدد",
    initialStock: 30,
    currentStock: 30,
    purchasePrice: 180_000,
    salePrice: 290_000,
    reorderPoint: 8,
    showInOnlinePriceList: false,
    createdAt: daysAgoIso(20),
    updatedAt: daysAgoIso(20),
  },

  // خدمات
  {
    id: "s-201",
    type: "SERVICE",
    name: "نصب ویندوز و درایورها",
    description: "نصب کامل سیستم‌عامل به همراه درایورها و نرم‌افزارهای پایه",
    categoryId: "cat-4",
    servicePrice: 350_000,
    showInOnlinePriceList: true,
    createdAt: daysAgoIso(18),
    updatedAt: daysAgoIso(18),
  },
  {
    id: "s-202",
    type: "SERVICE",
    name: "مشاوره مالی یک ساعته",
    description: "جلسهٔ مشاوره برای تنظیم دفاتر و گزارش‌های مالی",
    categoryId: "cat-5",
    servicePrice: 500_000,
    showInOnlinePriceList: true,
    createdAt: daysAgoIso(15),
    updatedAt: daysAgoIso(15),
  },
  {
    id: "s-203",
    type: "SERVICE",
    name: "سرویس دوره‌ای لپ‌تاپ",
    description: "تمیزکاری، تعوییر خمیر سیلیکون و بررسی سخت‌افزار",
    categoryId: "cat-4",
    servicePrice: 280_000,
    showInOnlinePriceList: false,
    createdAt: daysAgoIso(10),
    updatedAt: daysAgoIso(10),
  },
];

export const SEED_MOVEMENTS: StockMovement[] = [
  // روغن: ورود اولیه، خروج، ورود دوباره
  {
    id: "m-1",
    productId: "p-101",
    type: "ENTRY",
    quantity: 48,
    unit: "بطری",
    date: daysAgoIso(40),
    description: "موجودی اولیه هنگام ساخت کالا",
    source: "INITIAL",
    createdAt: nowIso(),
  },
  {
    id: "m-2",
    productId: "p-101",
    type: "EXIT",
    quantity: 10,
    unit: "بطری",
    date: daysAgoIso(12),
    description: "خروج از انبار",
    source: "MANUAL",
    createdAt: nowIso(),
  },
  {
    id: "m-3",
    productId: "p-101",
    type: "ENTRY",
    quantity: 4,
    unit: "بطری",
    date: daysAgoIso(3),
    description: "ورود کالا",
    source: "MANUAL",
    createdAt: nowIso(),
  },

  // کابل: خروج تا رو به اتمام
  {
    id: "m-4",
    productId: "p-102",
    type: "ENTRY",
    quantity: 10,
    unit: "عدد",
    date: daysAgoIso(35),
    description: "موجودی اولیه هنگام ساخت کالا",
    source: "INITIAL",
    createdAt: nowIso(),
  },
  {
    id: "m-5",
    productId: "p-102",
    type: "EXIT",
    quantity: 7,
    unit: "عدد",
    date: daysAgoIso(6),
    description: "خروج از انبار",
    source: "MANUAL",
    createdAt: nowIso(),
  },

  // هدفون: ناموجود
  {
    id: "m-6",
    productId: "p-103",
    type: "ENTRY",
    quantity: 5,
    unit: "عدد",
    date: daysAgoIso(30),
    description: "موجودی اولیه هنگام ساخت کالا",
    source: "INITIAL",
    createdAt: nowIso(),
  },
  {
    id: "m-7",
    productId: "p-103",
    type: "EXIT",
    quantity: 5,
    unit: "عدد",
    date: daysAgoIso(8),
    description: "خروج کامل از انبار",
    source: "MANUAL",
    createdAt: nowIso(),
  },

  // برنج و تیشرت
  {
    id: "m-8",
    productId: "p-104",
    type: "ENTRY",
    quantity: 20,
    unit: "کیسه",
    date: daysAgoIso(25),
    description: "موجودی اولیه هنگام ساخت کالا",
    source: "INITIAL",
    createdAt: nowIso(),
  },
  {
    id: "m-9",
    productId: "p-104",
    type: "EXIT",
    quantity: 3,
    unit: "کیسه",
    date: daysAgoIso(5),
    description: "خروج از انبار",
    source: "MANUAL",
    createdAt: nowIso(),
  },
  {
    id: "m-10",
    productId: "p-105",
    type: "ENTRY",
    quantity: 30,
    unit: "عدد",
    date: daysAgoIso(20),
    description: "موجودی اولیه هنگام ساخت کالا",
    source: "INITIAL",
    createdAt: nowIso(),
  },
  {
    id: "m-11",
    productId: "p-105",
    type: "EXIT",
    quantity: 6,
    unit: "عدد",
    date: daysAgoIso(2),
    description: "خروج از انبار",
    source: "MANUAL",
    createdAt: nowIso(),
  },

  /* ---------- حرکات متصل به فاکتورها (فاز ۴) ----------
     این حرکات اثر فاکتورهای فروش/خرید نمونه روی موجودی هستند و
     با حرکات دستی ورود/خروج (که اثر مالی ندارند) فرق دارند. */
  {
    id: "m-inv-1001",
    productId: "p-101",
    type: "EXIT",
    quantity: 6,
    unit: "بطری",
    date: daysAgoIso(12),
    description: "فروش با فاکتور INV-1001",
    source: "INVOICE",
    invoiceId: "inv-1001",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1002a",
    productId: "p-104",
    type: "EXIT",
    quantity: 5,
    unit: "کیسه",
    date: daysAgoIso(5),
    description: "فروش با فاکتور INV-1002",
    source: "INVOICE",
    invoiceId: "inv-1002",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1002b",
    productId: "p-105",
    type: "EXIT",
    quantity: 4,
    unit: "عدد",
    date: daysAgoIso(5),
    description: "فروش با فاکتور INV-1002",
    source: "INVOICE",
    invoiceId: "inv-1002",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1003a",
    productId: "p-101",
    type: "EXIT",
    quantity: 20,
    unit: "بطری",
    date: daysAgoIso(2),
    description: "فروش با فاکتور INV-1003",
    source: "INVOICE",
    invoiceId: "inv-1003",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1003b",
    productId: "p-102",
    type: "EXIT",
    quantity: 10,
    unit: "عدد",
    date: daysAgoIso(2),
    description: "فروش با فاکتور INV-1003",
    source: "INVOICE",
    invoiceId: "inv-1003",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1003c",
    productId: "p-104",
    type: "EXIT",
    quantity: 8,
    unit: "کیسه",
    date: daysAgoIso(2),
    description: "فروش با فاکتور INV-1003",
    source: "INVOICE",
    invoiceId: "inv-1003",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1004a",
    productId: "p-101",
    type: "ENTRY",
    quantity: 12,
    unit: "بطری",
    date: daysAgoIso(9),
    description: "خرید با فاکتور INV-1004",
    source: "INVOICE",
    invoiceId: "inv-1004",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1004b",
    productId: "p-102",
    type: "ENTRY",
    quantity: 10,
    unit: "عدد",
    date: daysAgoIso(9),
    description: "خرید با فاکتور INV-1004",
    source: "INVOICE",
    invoiceId: "inv-1004",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1004c",
    productId: "p-104",
    type: "ENTRY",
    quantity: 6,
    unit: "کیسه",
    date: daysAgoIso(9),
    description: "خرید با فاکتور INV-1004",
    source: "INVOICE",
    invoiceId: "inv-1004",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1005",
    productId: "p-105",
    type: "ENTRY",
    quantity: 10,
    unit: "عدد",
    date: daysAgoIso(1),
    description: "خرید با فاکتور INV-1005",
    source: "INVOICE",
    invoiceId: "inv-1005",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1007a",
    productId: "p-101",
    type: "EXIT",
    quantity: 10,
    unit: "بطری",
    date: daysAgoIso(3),
    description: "فروش با فاکتور INV-1007",
    source: "INVOICE",
    invoiceId: "inv-1007",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1007b",
    productId: "p-104",
    type: "EXIT",
    quantity: 2,
    unit: "کیسه",
    date: daysAgoIso(3),
    description: "فروش با فاکتور INV-1007",
    source: "INVOICE",
    invoiceId: "inv-1007",
    createdAt: nowIso(),
  },
  {
    id: "m-inv-1008",
    productId: "p-102",
    type: "ENTRY",
    quantity: 20,
    unit: "عدد",
    date: daysAgoIso(4),
    description: "خرید با فاکتور INV-1008",
    source: "INVOICE",
    invoiceId: "inv-1008",
    createdAt: nowIso(),
  },
];
